version: '3'

services:
    nginx-api:
        image: nginx:latest
        container_name: coffee-nginx
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8097:80"
        volumes:
            - ./:/var/www/html
            - ./docker/images/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - coffee_net

    postgre-api:
        image: postgres:11.5
        container_name: coffe-postgre
        ports:
            - "5453:5432"
        environment:
            POSTGRES_PASSWORD: coffee
            POSTGRES_USER: coffee
        volumes:
            - postgree-coffee-vol:/var/lib/postgresql/data
        networks:
            -  coffee_net

    coffee_php-cli:
        build: docker/images/php-cli
        container_name: coffee_php-cli
        volumes:
            - ./:/var/www/html
        networks:
            - coffee_net
        expose:
            - 9000

networks:
    coffee_net:
        external: true
volumes:
    data:
        driver: "local"
    postgree-coffee-vol:
