version: '3'

services:
    nginx-api:
        image: nginx:latest
        container_name: coffeee-nginx
        ports:
            - "8097:80"
        volumes:
            - ./:/var/www/html
            - ./docker/images/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - coffeee_net

    mysql:
        image: coffeee.mysql
        container_name: coffeee.mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'coffeee'
            MYSQL_DATABASE: 'coffeee'
            MYSQL_USER: 'coffeee'
            MYSQL_PASSWORD: 'coffeee'
        ports:
            - "3305:3306"
        networks:
            coffeee_net:
        tty: true

    coffeee_php-cli:
        build: docker/images/php-cli
        container_name: coffeee_php-cli
        volumes:
            - ./:/var/www/html
        networks:
            - coffeee_net
        expose:
            - 9000

networks:
    coffeee_net:
        external: true
